import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { headers } from "next/headers";
import "./globals.css";
import "@/styles/layout.css";
import Navbar from "@/components/navbar";
import Sidebar from "@/components/sidebar";
import { SidebarProvider } from "@/hooks/useSidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headerList = await headers();
  const current_url = headerList.get("x-url");
  console.log(current_url);
  return (
      <SidebarProvider>
        <html lang="en">
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-700 text-white`}
          >
            <div className="wrapper flex w-full h-[100vh] overflow-hidden">
              <Sidebar />
              <div className="main-content flex w-full h-full flex-col overflow-hidden">
                <Navbar />
                <div className="content">{children}</div>
              </div>
            </div>
          </body>
        </html>
      </SidebarProvider>
  );
}
