apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: wtnbhogehoge/backend:1.1
          ports:
            - containerPort: 3030
          resources:
            limits:
              memory: "4Gi"
              cpu: "2"
            requests:
              memory: "1Gi"
              cpu: "1"